### ISSUE TITLE
error when loading model

### ISSUE THREAD

**Issue by ZhangChen0212** [fcakyon/yolov5-pip#103]
Hi there! Currently I'm running it in Raspberry Pi 3B, and YOLOv5 actually works in terminal. Then I expect it to run in python, so I copied the code in Using from Python (basic), but it raises series of errors: 

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f83f6b9a0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /ultralytics/yolov5/master/data/images/zidane.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f83f6b9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chen/Desktop/test_1.py", line 10, in <module>
    results = model(img)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/yolov5/models/common.py", line 547, in forward
    im, f = Image.open(requests.get(im, stream=True).raw if str(im).startswith('http') else im), im
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /ultralytics/yolov5/master/data/images/zidane.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f83f6b9a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

Any reply will be greatly appreciated!

**Comment by fcakyon** [comment]
@ZhangChen0212 it means that you dont have internet connection to download the `zidane.jpg` :)

**Comment by fcakyon** [comment]
@ZhangChen0212 i am not able recreate the issue.
Can you provide your model file?
What is the format?
Is it a TF/TFLite model?

**Comment by fcakyon** [comment]
@ZhangChen0212 this pr should fix this issue: https://github.com/fcakyon/yolov5-pip/pull/104

Can you please update your `yolov5` from main branch and see if the bug is solved?

```bash
pip uninstall yolov5
```
```bash
pip install git+https://github.com/fcakyon/yolov5-pip.git
```

**Comment by ZhangChen0212** [comment]
> @ZhangChen0212 i am not able recreate the issue. Can you provide your model file? What is the format? Is it a TF/TFLite model?

It is a pt model.

**Comment by ZhangChen0212** [comment]
> @ZhangChen0212 this pr should fix this issue: #104
> 
> Can you please update your `yolov5` from main branch and see if the bug is solved?
> 
> ```shell
> pip uninstall yolov5
> ```
> 
> ```shell
> pip install git+https://github.com/fcakyon/yolov5-pip.git
> ```

I did: 
`pip3 install git+https://github.com/fcakyon/yolov5-pip.git`

Got: 
```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/fcakyon/yolov5-pip.git
  Cloning https://github.com/fcakyon/yolov5-pip.git to /tmp/pip-req-build-g6fh45vr
  Running command git clone -q https://github.com/fcakyon/yolov5-pip.git /tmp/pip-req-build-g6fh45vr
  fatal: unable to access 'https://github.com/fcakyon/yolov5-pip.git/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
WARNING: Discarding git+https://github.com/fcakyon/yolov5-pip.git. Command errored out with exit status 128: git clone -q https://github.com/fcakyon/yolov5-pip.git /tmp/pip-req-build-g6fh45vr Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone -q https://github.com/fcakyon/yolov5-pip.git /tmp/pip-req-build-g6fh45vr Check the logs for full command output.
```

**Comment by fcakyon** [comment]
@ZhangChen0212 are you sure you have internet access?

**Comment by ZhangChen0212** [comment]
> @ZhangChen0212 are you sure you have internet access?

![image](https://user-images.githubusercontent.com/61965406/165380520-04050f24-442e-43aa-9292-c32379b49c93.png)
I do have internet access.

**Comment by fcakyon** [comment]
@ZhangChen0212 I am not getting this error when I try `pip install git+https://github.com/fcakyon/yolov5-pip.git`

**Comment by fcakyon** [comment]
Then you can:

```bash
git clone https://github.com/fcakyon/yolov5-pip
cd yolov5-pip
pip install .
```

**Comment by ZhangChen0212** [comment]
> Then you can:
> 
> ```shell
> git clone https://github.com/fcakyon/yolov5-pip
> cd yolov5-pip
> pip install .
> ```

Thanks! But it still leads to the same error: 
```
Traceback (most recent call last):
  File "/home/chen/Desktop/test_1.py", line 10, in <module>
    results = model(img)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/yolov5/models/common.py", line 568, in forward
    y = self.model(x, augment, profile)  # forward
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/yolov5/models/common.py", line 456, in forward
    input, output = self.input_details[0], self.output_details[0]
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 947, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DetectMultiBackend' object has no attribute 'input_details'
```

**Comment by fcakyon** [comment]
@ZhangChen0212 i am not having that error, can you provide you model file?

**Comment by ZhangChen0212** [comment]
> @ZhangChen0212 i am not having that error, can you provide you model file?

[yolov5s.zip](https://github.com/fcakyon/yolov5-pip/files/8573197/yolov5s.zip)

**Comment by ZhangChen0212** [comment]
Can I somehow modify the code to use the model in the local path?




> @ZhangChen0212 i am not having that error, can you provide you model file?

**Comment by fcakyon** [comment]
@ZhangChen0212 for mp4 files you can use cli:

```bash
$ yolov5 detect --weights yolov5s.pt --source 0  # webcam
                                              file.jpg  # image
                                              file.mp4  # video
                                              path/  # directory
                                              path/*.jpg  # glob
                                              rtsp://170.93.143.139/rtplive/470011e600ef003a004ee33696235daa  # rtsp stream
                                              rtmp://192.168.1.105/live/test  # rtmp stream
                                              http://112.50.243.8/PLTV/88888888/224/3221225900/1.m3u8  # http stream
```

**Comment by fcakyon** [comment]
@ZhangChen0212 can you please star the repo if you like it 🚀

**Comment by ZhangChen0212** [comment]
> or use `detect` module:
> 
> ```python
> from yolov5 import detect
> 
> video_path = 'file.mp4'
> 
> detect.run(source=video_path , weights="yolov5s6.pt", conf_thres=0.25, imgsz=640)
> ```

Thank you so much for all these help and this package!
