### ISSUE TITLE
Freeze cli argument error

### ISSUE THREAD

**Issue by thoron** [fcakyon/yolov5-pip#136]
When executing cli commands with freeze you will get an error:
Command:
```
!yolov5 train --img $img_size --data $data_set_yaml_file --epochs 10 --cache ram --batch -1 --freeze 10 --save_dir $runs_folder
```
Stacktrace:
```
Traceback (most recent call last):
  File "/usr/local/bin/yolov5", line 8, in <module>
    sys.exit(app())
  File "/usr/local/lib/python3.7/dist-packages/yolov5/cli.py", line 16, in app
    "export": export,
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/yolov5/train.py", line 743, in run_cli
    main(opt)
  File "/usr/local/lib/python3.7/dist-packages/yolov5/train.py", line 634, in main
    train(opt.hyp, opt, device, callbacks)
  File "/usr/local/lib/python3.7/dist-packages/yolov5/train.py", line 197, in train
    freeze = [f'model.{x}.' for x in (freeze if len(freeze) > 1 else range(freeze[0]))]  # layers to freeze
TypeError: object of type 'int' has no len()
```

The `setattr` in the referenced line could be the culprit if it boxes lists into int

https://github.com/fcakyon/yolov5-pip/blob/41501a4ca96ef8e66a764e13ea122c719c200277/yolov5/train.py#L732

Short example of the possible issue:
```python
import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--freeze', nargs='+', type=int, default=[0], help='Freeze layers: backbone=10, first3=0 1 2')
args = parser.parse_known_args()[0]
print(args.freeze)
# [10]
setattr(args, 'freeze', 10)
print(args.freeze)
# 10
```

**Comment by fcakyon** [comment]
Have you tried providing it as list as `--freeze '[10,]'` or as `--freeze '10,'`?

**Comment by fcakyon** [comment]
I will try to inspect more to understand the issue

**Comment by fcakyon** [comment]
@thoron with the latest updates thisu usage is supported now: 
```bash
!yolov5 train --img $img_size --data $data_set_yaml_file --epochs 10 --cache ram --batch -1 --freeze 10 --save_dir $runs_folder
```
