### ISSUE TITLE
Exception when using --evolve

### ISSUE THREAD

**Issue by emillundh** [fcakyon/yolov5-pip#138]
Retraining on a custom dataset:
```
$ yolov5 train --imgsz 640 --batch-size 16 --epochs 5 --data train.yaml --weights yolov5s.pt --evolve
```
and after one epoch I receive the error
```
UnboundLocalError: local variable 'map50s' referenced before assignment
```

**Comment by fcakyon** [comment]
@emillundh can you please post the full error traceback?

**Comment by emillundh** [comment]
Sorry, here it comes
```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\path\to\.venv\Scripts\yolov5.exe\__main__.py", line 7, in <module>
    # To support running as a module (python -m microAeye) since no imports are relative
  File "C:\Users\path\to\.venv\lib\site-packages\yolov5\cli.py", line 11, in app
    fire.Fire(
  File "C:\Users\path\to\.venv\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\path\to\.venv\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\path\to\.venv\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\path\to\.venv\lib\site-packages\yolov5\train.py", line 743, in run_cli
    main(opt)
  File "C:\Users\path\to\.venv\lib\site-packages\yolov5\train.py", line 716, in main
    results = train(hyp.copy(), opt, device, callbacks)
  File "C:\Users\path\to\.venv\lib\site-packages\yolov5\train.py", line 433, in train
    log_vals = list(mloss) + list(results) + lr + list(maps) + list(map50s)
UnboundLocalError: local variable 'map50s' referenced before assignment
```

**Comment by emillundh** [comment]
Sorry here it comes
```
     Epoch   gpu_mem       box       obj       cls    labels  img_size
       0/1        0G    0.0891  0.009051         0        43       640: 100%|██████████| 2/2 [00:20<00:00, 10.45s/it]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\path\to\.venv\Scripts\yolov5.exe\__main__.py", line 7, in <module>
    # To support running as a module (python -m myscript) since no imports are relative
  File "C:\Users\path\to\.venv\lib\site-packages\yolov5\cli.py", line 11, in app
    fire.Fire(
  File "C:\Users\path\to\.venv\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\path\to\.venv\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\path\to\.venv\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\path\to\.venv\lib\site-packages\yolov5\train.py", line 743, in run_cli
    main(opt)
  File "C:\Users\path\to\.venv\lib\site-packages\yolov5\train.py", line 716, in main
    results = train(hyp.copy(), opt, device, callbacks)
  File "C:\Users\path\to\.venv\lib\site-packages\yolov5\train.py", line 433, in train
    log_vals = list(mloss) + list(results) + lr + list(maps) + list(map50s)
UnboundLocalError: local variable 'map50s' referenced before assignment
```
Actually I have no idea what the line "# To support running..." is doing - seems to come from my own code, but probably the traceback is not read correctly at that point, because the error itself was confirmed on two completely different machines!
```
Name: yolov5
Version: 6.1.8
```

**Comment by fcakyon** [comment]
thanks for the report! 

this pr should fix it: https://github.com/fcakyon/yolov5-pip/pull/139
