### ISSUE TITLE
Error occurred when using cli with gpu

### ISSUE THREAD

**Issue by xugaoxiang** [fcakyon/yolov5-pip#40]
python: 3.8
pytorch: 1.7.1 + cu101
yolov5-pip: latest

`(yolov5pip) xugaoxiang@1070Ti:~/workshop/github$ yolov5 detect --source zidane.jpg
YOLOv5 🚀 2021-9-15 torch 1.7.1+cu101 CUDA:0 (NVIDIA GeForce GTX 1070 Ti, 8116.4375MB)

Fusing layers...
Model Summary: 283 layers, 7276605 parameters, 0 gradients
Traceback (most recent call last):
  File "/home/xugaoxiang/anaconda3/envs/yolov5pip/bin/yolov5", line 8, in <module>
    sys.exit(app())
  File "/home/xugaoxiang/anaconda3/envs/yolov5pip/lib/python3.8/site-packages/yolov5/cli.py", line 11, in app
    fire.Fire(
  File "/home/xugaoxiang/anaconda3/envs/yolov5pip/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/xugaoxiang/anaconda3/envs/yolov5pip/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/xugaoxiang/anaconda3/envs/yolov5pip/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/xugaoxiang/anaconda3/envs/yolov5pip/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/xugaoxiang/anaconda3/envs/yolov5pip/lib/python3.8/site-packages/yolov5/detect.py", line 120, in run
    model(torch.zeros(1, 3, *imgsz).to(device).type_as(next(model.parameters())))  # run once
TypeError: zeros() argument after * must be an iterable, not int`

**Comment by fcakyon** [comment]
@xugaoxiang thanks a lot for your interest for the package! Would you mind sharing the command that you used?

**Comment by fcakyon** [comment]
@xugaoxiang thanks for you interest in the package! it would be fixed with v5.0.10, could you try it?
